### ISSUE TITLE
Does it remove discarded layers from cache? [Question]

### ISSUE THREAD

**Issue by FrozenAlex** [satackey/action-docker-layer-caching#104]
Does all of the cache gets hit at once so automatic removal won't work with it or how does it discard image layers that have been replaced on rebuild? 
Will it just fill up all of the remaining space in cache and just get deleted all together?

**Comment by rcowsill** [comment]
The layers are split into multiple caches, but they're loaded as a unit. That means that layers replaced on rebuild aren't discarded. This issue is discussed further in #55.

When the quota is used up GitHub starts deleting the oldest cache files to bring the total size for the repo under 5GB. That's likely to delete the "root" cache for the action, since it is always saved/loaded first. When that happens a new layer cache will be created from scratch, and the layers from the old cache will get discarded after 7 days since they're no longer used.
